name: Build Every Commit

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-darwin:
        runs-on: macOS-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    cmake -B build .
                    cmake --build build -- all
            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: hello_darwin_${{github.sha}}
                    path: build/hello_darwin

    build-linux:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    cmake -B build .
                    cmake --build build -- all
            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: hello_linux_${{github.sha}}
                    path: build/hello_linux

    build-windows-x86:
        runs-on: windows-2019
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
                    cmake -GNinja -B build .
                    cmake --build build -- all
            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: hello_windows_x86_${{github.sha}}
                    path: build/hello_windows_x86.exe

    build-windows-x64:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    submodules: recursive
            -   name: Build
                shell: cmd
                run: |
                    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
                    cmake -GNinja -B build .
                    cmake --build build -- all
            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: hello_windows_x64_${{github.sha}}
                    path: build/hello_windows_x64.exe
